### ISSUE TITLE
Native functions

### ISSUE THREAD

**Issue by dy** [AGhost-7/to-source#1]
Hi @AGhost-7 !
Nice package.
There is an issue with stringifying native objects/functions.
Example:

``` js
var source = require('to-source');
source(Math.log); //→ function () {}
```

Probably it would be better it to return native object 'Math.log', than undefined function. Or at least print warning to the console.

**Comment by AGhost-7** [comment]
By default it returns an empty function for any kind of function. It you override the formatter you can make it use `toString` on functions.

Its still going to be a problem for native stuff. Here's what I'm thinking:

``` javascript
var globalScope = this;
function fnToString(fn) {
  var str = fn.toString();
  // going to need to use a regex, but you get the idea.
  if(str === 'function log() { [native code] }') {
    ... search for function name in global scope
  }
  return str;
}
```

Its unreliable at best, since in some cases globals are defined by libraries, so it will output non-native functions in some cases. The only other alternative I can think of is using a map containing everything that's native,

``` javascript
var nativeFns = {};
nativeFns[Math.log] = 'Math.log';
function fnToString(fn) {
  var str = nativeFns[fn];
  if(nativeFns) {
    return str;
  } else {
    return fn.toString();
  }
}
```

Any other ideas for handling this? Honestly that's part of the reason why I left functions out since its pretty hard to support when you start thinking about it.

**Comment by dy** [comment]
Actually I wonder why you dont use function.toString() - it returns pretty much valid code.

**Comment by AGhost-7** [comment]
Not if the function closes over variables, which is very common because usually you `require` some library or another to use in your function.

``` javascript
var fs = require('fs');
var jsonToFile = function(fileName, js) {
    fs.appendFileSync(fileName, JSON.stringify(js));
};
console.log(jsonToFile.toString());
// => function (fileName, js) {
// =>       fs.appendFileSync(fileName, JSON.stringify(js));
// => }
```

I left this out since its not very reliable imo.

**Comment by dy** [comment]
I see. Well there seem to be no good solution. Inserting polyfills code is not an option. Guess ticked may be closed then...

**Comment by AGhost-7** [comment]
I can try to add this, but I think I'll keep it disabled by default.

**Comment by dy** [comment]
There is also node addons

**Comment by AGhost-7** [comment]
Yea I don't think there's really a way to support those since they're require'd into the scope. I'll try to add support for `Object.defineProperty`, etc.

**Comment by AGhost-7** [comment]
Added limited support to native stuff; its just targeting language builtins. If you can think of a way to add broader support I'm all ears.
